version : '3.9'

networks:
  mynet:


services:

  php5.6:
    build: .
    container_name: php5.6
    volumes:
      - ./src:/var/www/html
      - ./php_conf:/etc/php5/fpm/pool.d/
    command:
      - ./run.sh
    networks:
      - mynet
    depends_on: 
      - mysql

  mysql:
    image: mysql:5.6
    container_name: mysql5.6
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: docker
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/dump:/docker-entrypoint-initdb.d
      - ./mysql/log:/var/log/mysql
    networks:
      - mynet  

  nginx:
    image: nginx:1.18
    container_name: nginx-php5
    ports:
     - "8085:80"
    volumes:
     - ./src:/var/www/html
     - ./nginx_conf:/etc/nginx/
     - ./nginx_conf:/etc/nginx/conf.d/
    command: 
      - ln -sf /dev/stdout /var/log/nginx/access.log && \
      - ln -sf /dev/stderr /var/log/nginx/error.log && \
      - ln -sf /dev/stderr /var/log/php-fpm.log
    networks:
      - mynet
    depends_on:
      - php5.6

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_PORT: 13306
      PMA_HOST: mysql
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: docker
    networks:
      - mynet
    depends_on:
      - mysql
